import pandas as pd
import sys
import os

# Configuration
input_file = '/Users/hyeonhotak/Downloads/코딩/convum-crm/컨범코리아_CRM구축_업체명.xlsx'
output_file = '/Users/hyeonhotak/Downloads/코딩/convum-crm/src/sql/import_companies.sql'
sheet_name = '고객DB'

def escape_sql(val):
    if pd.isna(val) or val == '':
        return 'NULL'
    # Escape single quotes
    val_str = str(val).strip()
    if val_str == '':
        return 'NULL'
    return "'" + val_str.replace("'", "''") + "'"

def main():
    print(f"Reading Excel file: {input_file}")
    try:
        df = pd.read_excel(input_file, sheet_name=sheet_name)
    except Exception as e:
        print(f"Error reading Excel file: {e}")
        sys.exit(1)

    print(f"Original row count: {len(df)}")
    
    # Deduplicate by '업체명'
    # Keep the first occurrence
    df_dedup = df.drop_duplicates(subset=['업체명'], keep='first')
    print(f"Deduplicated row count: {len(df_dedup)}")

    print(f"Generating SQL file: {output_file}")
    
    sql_statements = []
    sql_statements.append("-- Import company data from Excel '고객DB' sheet")
    sql_statements.append("-- Generated by generate_companies_import.py")
    sql_statements.append("-- WARNING: This script TRUNCATES the accounts table!")
    sql_statements.append("")
    sql_statements.append("TRUNCATE TABLE accounts CASCADE;")
    sql_statements.append("")
    sql_statements.append("INSERT INTO accounts (id, name, industry, main_phone, website, address, registration_date)")
    sql_statements.append("VALUES")

    values_list = []
    
    # Generate IDs sequentially: C-001, C-002, ...
    for i, (index, row) in enumerate(df_dedup.iterrows()):
        account_id = f"'C-{i+1:03d}'"
        
        name = escape_sql(row.get('업체명'))
        if name == 'NULL':
            continue # Skip if no name
            
        industry = escape_sql(row.get('업종'))
        main_phone = escape_sql(row.get('대표전화'))
        website = escape_sql(row.get('홈페이지'))
        address = escape_sql(row.get('주소'))
        # owner column is removed from schema
        # owner = escape_sql(row.get('등록자'))
        
        # Format date
        reg_date_raw = row.get('등록일')
        if pd.isna(reg_date_raw):
            registration_date = 'NULL'
        else:
            try:
                registration_date = "'" + pd.to_datetime(reg_date_raw).strftime('%Y-%m-%d') + "'"
            except:
                registration_date = 'NULL'

        value_row = f"  ({account_id}, {name}, {industry}, {main_phone}, {website}, {address}, {registration_date})"
        values_list.append(value_row)

    if values_list:
        sql_statements.append(",\n".join(values_list))
        sql_statements.append(";")
        
        # Write to file
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("\n".join(sql_statements))
        print("Success!")
    else:
        print("No data found to generate SQL.")

if __name__ == "__main__":
    main()
