import pandas as pd
import sys
import os

# Configuration
input_file = '/Users/hyeonhotak/Downloads/코딩/convum-crm/컨범코리아_CRM구축_데이터베이스.xlsx'
output_file = '/Users/hyeonhotak/Downloads/코딩/convum-crm/src/sql/accounts_import_fixed.sql'
sheet_name = '고객DB'

def escape_sql(val):
    if pd.isna(val) or val == '':
        return 'NULL'
    # Escape single quotes
    val_str = str(val).strip()
    if val_str == '':
        return 'NULL'
    return "'" + val_str.replace("'", "''") + "'"

def main():
    print(f"Reading Excel file: {input_file}")
    try:
        df = pd.read_excel(input_file, sheet_name=sheet_name)
    except Exception as e:
        print(f"Error reading Excel file: {e}")
        sys.exit(1)

    print(f"Generating SQL file: {output_file}")
    
    sql_statements = []
    sql_statements.append("-- Import accounts data from Excel '고객DB' sheet")
    sql_statements.append("-- Generated by generate_accounts_import_fixed.py")
    sql_statements.append("")
    
    # Accounts Table
    sql_statements.append("-- Accounts Table Upsert")
    sql_statements.append("INSERT INTO accounts (id, name, industry, main_phone)")
    sql_statements.append("VALUES")

    accounts_values = []
    contacts_values = []
    
    for index, row in df.iterrows():
        # Map columns
        # No -> id
        account_id = escape_sql(row.get('No'))
        if account_id == 'NULL': # Skip rows without ID
            continue
            
        name = escape_sql(row.get('업체명'))
        industry = escape_sql(row.get('업종'))
        # type, owner, grade are dropped from accounts schema
        # acc_type = escape_sql(row.get('거래상태')) 
        # owner = escape_sql(row.get('담당영업'))
        # grade = escape_sql(row.get('등급'))
        
        main_phone = escape_sql(row.get('대표전화'))
        
        # Contact info
        contact_name = escape_sql(row.get('담당자명'))
        phone = escape_sql(row.get('휴대전화'))
        email = escape_sql(row.get('이메일'))
        position = escape_sql(row.get('직급'))
        department = escape_sql(row.get('부서'))
        note = escape_sql(row.get('비고'))

        # Accounts row
        # contact_name is dropped from accounts schema, so we don't insert it there.
        acc_row = f"  ({account_id}, {name}, {industry}, {main_phone})"
        accounts_values.append(acc_row)
        
        # Contacts row
        # Only insert if there is contact info
        if contact_name != 'NULL' or phone != 'NULL' or email != 'NULL':
            if contact_name != 'NULL':
                contact_row = f"  ({account_id}, {contact_name}, {position}, {department}, {phone}, {email}, {note})"
                contacts_values.append(contact_row)

    if accounts_values:
        sql_statements.append(",\n".join(accounts_values))
        sql_statements.append("ON CONFLICT (id) DO UPDATE SET")
        sql_statements.append("  name = EXCLUDED.name,")
        sql_statements.append("  industry = EXCLUDED.industry,")
        sql_statements.append("  main_phone = EXCLUDED.main_phone;")
        
        sql_statements.append("")
        sql_statements.append("-- Contacts Table Insert")
        sql_statements.append("-- Note: Using ON CONFLICT DO NOTHING or similar might be needed if re-running, but contacts has UUID PK.")
        sql_statements.append("-- We will just INSERT. To avoid duplicates on re-run, one might need to clear contacts for these accounts first.")
        sql_statements.append("-- For now, simple INSERT.")
        sql_statements.append("INSERT INTO contacts (account_id, name, position, department, phone, email, memo)")
        sql_statements.append("VALUES")
        
        if contacts_values:
            sql_statements.append(",\n".join(contacts_values))
            sql_statements.append(";")
        else:
            sql_statements.append("-- No contact data found")
        
        # Write to file
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("\n".join(sql_statements))
        print("Success!")
    else:
        print("No data found to generate SQL.")

if __name__ == "__main__":
    main()
