import pandas as pd
import sys
import os

# Configuration
input_file = '/Users/hyeonhotak/Downloads/코딩/convum-crm/컨범코리아_CRM구축_데이터베이스.xlsx'
output_file = '/Users/hyeonhotak/Downloads/코딩/convum-crm/src/sql/import_contacts.sql'
sheet_name = '고객DB'

def escape_sql(val):
    if pd.isna(val) or val == '':
        return 'NULL'
    # Escape single quotes
    val_str = str(val).strip()
    if val_str == '':
        return 'NULL'
    return "'" + val_str.replace("'", "''") + "'"

def main():
    print(f"Reading Excel file: {input_file}")
    try:
        df = pd.read_excel(input_file, sheet_name=sheet_name)
    except Exception as e:
        print(f"Error reading Excel file: {e}")
        sys.exit(1)

    print(f"Total row count: {len(df)}")
    
    # Step 1: Reconstruct Company IDs
    # Deduplicate by '업체명' to match import_companies.sql logic
    df_companies = df.drop_duplicates(subset=['업체명'], keep='first')
    
    company_id_map = {}
    for i, (index, row) in enumerate(df_companies.iterrows()):
        company_name = str(row.get('업체명')).strip()
        account_id = f"C-{i+1:03d}"
        company_id_map[company_name] = account_id
        
    print(f"Mapped {len(company_id_map)} companies.")

    print(f"Generating SQL file: {output_file}")
    
    sql_statements = []
    sql_statements.append("-- Import contact data from Excel '고객DB' sheet")
    sql_statements.append("-- Generated by generate_contacts_import.py")
    sql_statements.append("-- WARNING: This script TRUNCATES the contacts table!")
    sql_statements.append("")
    sql_statements.append("TRUNCATE TABLE contacts CASCADE;")
    sql_statements.append("")
    sql_statements.append("INSERT INTO contacts (account_id, name, position, department, phone, email, memo, grade, sales_rep, status, source)")
    sql_statements.append("VALUES")

    values_list = []
    
    # Step 2: Generate Contact Inserts
    for index, row in df.iterrows():
        company_name = str(row.get('업체명')).strip()
        account_id_raw = company_id_map.get(company_name)
        
        if not account_id_raw:
            print(f"Warning: No Account ID found for company '{company_name}'")
            continue
            
        account_id = f"'{account_id_raw}'"
        
        name = escape_sql(row.get('담당자명'))
        if name == 'NULL':
             continue

        position = escape_sql(row.get('직급'))
        department = escape_sql(row.get('부서'))
        phone = escape_sql(row.get('휴대전화'))
        email = escape_sql(row.get('이메일'))
        memo = escape_sql(row.get('비고'))
        
        # New columns
        grade = escape_sql(row.get('등급'))
        sales_rep = escape_sql(row.get('담당영업'))
        status = escape_sql(row.get('거래상태'))
        source = escape_sql(row.get('유입경로'))

        value_row = f"  ({account_id}, {name}, {position}, {department}, {phone}, {email}, {memo}, {grade}, {sales_rep}, {status}, {source})"
        values_list.append(value_row)

    if values_list:
        sql_statements.append(",\n".join(values_list))
        sql_statements.append(";")
        
        # Write to file
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write("\n".join(sql_statements))
        print(f"Success! Generated {len(values_list)} contact inserts.")
    else:
        print("No contact data found to generate SQL.")

if __name__ == "__main__":
    main()
